# Generated by Django 5.2 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavetype_payment_percentage_leavetype_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('fully_paid', 'Fully Paid'), ('half_paid', 'Half Paid'), ('unpaid', 'Unpaid'), ('custom', 'Custom')], help_text='Specifies how leave days are paid: fully, half, unpaid, or custom percentage', max_length=20, null=True, verbose_name='Payment Type'),
        ),
    ]
