# Generated by Django 5.2 on 2026-06-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leavetype_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='exclude_during_probation',
            field=models.BooleanField(default=False, verbose_name='Block During Probation'),
        ),
    ]
