# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('leave', '0005_leavetype_exclude_during_probation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableleave',
            name='leave_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_available_leave', to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AlterField(
            model_name='companyleave',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='leave_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='leave_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_created', to='employee.employee', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
