# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_compensatoryleaverequestcomment_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='leaverequestfile',
            name='file',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Icon'),
        ),
    ]
