# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('helpdesk', '0002_alter_historicalticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmanager',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.faqcategory'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='employee.employee', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
