# Generated by Django 5.2 on 2026-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_recruitmentgeneralsetting_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='zip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PIN Code'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='zip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PIN Code'),
        ),
    ]
