# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('recruitment', '0005_alter_candidate_zip_alter_historicalcandidate_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruitment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='recruitment.recruitment', verbose_name='Recruitment'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.stage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='document_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidatedocumentrequest'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rating', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rating', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='job_position_id',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='linkedin_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.linkedinaccount', verbose_name='LinkedIn Account'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='job_position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='recruitment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment', verbose_name='Recruitment'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_candidate', to='recruitment.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillzonecandidate_set', to='recruitment.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='skill_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillzonecandidate_set', to='recruitment.skillzone', verbose_name='Skill Zone'),
        ),
    ]
