# Generated by Django 5.2 on 2026-06-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylinx_meet', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googlemeeting',
            new_name='skylinx_mee_employe_bb8271_idx',
            old_name='skylinx_mee_employe_32e027_idx',
        ),
        migrations.RenameIndex(
            model_name='googlemeeting',
            new_name='skylinx_mee_event_i_3ef04f_idx',
            old_name='skylinx_mee_event_i_4a80d4_idx',
        ),
    ]
