# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('skylinx_meet', '0002_rename_skylinx_mee_employe_32e027_idx_skylinx_mee_employe_bb8271_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecloudcredential',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
