# Generated by Django 5.2 on 2026-06-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tracklatecomeearlyout_company_id_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.employeetype', verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.jobposition', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.worktype', verbose_name='Work Mode'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.employeetype', verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposition', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.worktype', verbose_name='Work Mode'),
        ),
    ]
