# Generated by Django 5.2 on 2026-06-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_badge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit UIDAI Aadhaar number', max_length=12, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], max_length=10, null=True, verbose_name='Bank Account Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number — 10 chars, e.g. ABCDE1234F', max_length=10, null=True, unique=True, verbose_name='PAN Number'),
        ),
    ]
