# Generated by Django 5.2 on 2026-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_add_india_identity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee ID / Badge ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIN Code'),
        ),
    ]
