# Generated by Django 5.2 on 2026-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_badge_id_alter_employee_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10, null=True, verbose_name='Bank Account Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=50, null=True),
        ),
    ]
