# Generated by Django 5.2 on 2026-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_account_type_alter_employee_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='accepted_employees',
            field=models.ManyToManyField(blank=True, related_name='accepted_policies', to='employee.employee', verbose_name='Accepted Employees'),
        ),
    ]
