# Generated by Django 5.2 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_end',
            field=models.DateField(blank=True, null=True, verbose_name='Probation End Date'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_end',
            field=models.DateField(blank=True, null=True, verbose_name='Probation End Date'),
        ),
    ]
