# Generated by Django 6.0.6 on 2026-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeeworkinformation_probation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='probation_end',
        ),
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='salary_hour',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='probation_end',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='salary_hour',
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
    ]
