# Generated by Django 6.0.6 on 2026-06-23 13:20

from django.db import migrations, models


def drop_if_exists_sql(table, column):
    """Drop a column if it exists, silently skipping on SQLite builds that lack support."""
    def _drop(apps, schema_editor):
        try:
            schema_editor.execute(
                f"ALTER TABLE {schema_editor.quote_name(table)} DROP COLUMN {schema_editor.quote_name(column)}"
            )
        except Exception:
            pass  # Column doesn't exist or DB doesn't support this syntax
    return migrations.RunPython(_drop, migrations.RunPython.noop)


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeeworkinformation_probation_end_and_more'),
    ]

    operations = [
        # Use IF EXISTS so this is safe on DBs that already lack these columns.
        drop_if_exists_sql("employee_employeeworkinformation", "basic_salary"),
        drop_if_exists_sql("employee_employeeworkinformation", "probation_end"),
        drop_if_exists_sql("employee_employeeworkinformation", "salary_hour"),
        drop_if_exists_sql("employee_historicalemployeeworkinformation", "basic_salary"),
        drop_if_exists_sql("employee_historicalemployeeworkinformation", "probation_end"),
        drop_if_exists_sql("employee_historicalemployeeworkinformation", "salary_hour"),

        migrations.AddField(
            model_name='employeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
    ]
