# Generated by Django 6.0.6 on 2026-06-23 13:20

from django.db import migrations, models


def drop_if_exists(table, column):
    return migrations.RunSQL(
        sql=f"ALTER TABLE {table} DROP COLUMN IF EXISTS {column};",
        reverse_sql=migrations.RunSQL.noop,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeeworkinformation_probation_end_and_more'),
    ]

    operations = [
        # Use IF EXISTS so this is safe on DBs that already lack these columns.
        drop_if_exists("employee_employeeworkinformation", "basic_salary"),
        drop_if_exists("employee_employeeworkinformation", "probation_end"),
        drop_if_exists("employee_employeeworkinformation", "salary_hour"),
        drop_if_exists("employee_historicalemployeeworkinformation", "basic_salary"),
        drop_if_exists("employee_historicalemployeeworkinformation", "probation_end"),
        drop_if_exists("employee_historicalemployeeworkinformation", "salary_hour"),

        migrations.AddField(
            model_name='employeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Probation Period (Days)'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of CTC: e.g. {"basic": 50, "hra": 20, "other": 30}', null=True, verbose_name='Salary Components'),
        ),
    ]
