# Generated by Django 6.0.6 on 2026-06-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_company_skylinx_to_emplinx'),
        ('employee', '0015_employeetag_company_id_notefiles_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
