# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('employee', '0016_alter_employeeworkinformation_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employeetype', verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.jobposition', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.jobrole', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_manager', to='employee.employee', verbose_name='Reporting Manager'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.worktype', verbose_name='Work Mode'),
        ),
    ]
