# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_actiontype_company_id_policymultiplefile_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_profile',
            field=models.ImageField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='notefiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='attachment',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
