# Generated by Django 4.2.30 on 2026-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_backfill_single_company_org_settings'),
        ('employee', '0020_policy_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employeetype', verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobposition', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobrole', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_manager', to='employee.employee', verbose_name='Reporting Manager'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.worktype', verbose_name='Work Mode'),
        ),
    ]
