# Generated by Django 4.2.30 on 2026-07-04 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employeeworkinformation_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qualification_detail',
            field=models.CharField(blank=True, help_text='e.g. Diploma, Inter, B.Tech CSE, MBA HR', max_length=100, null=True, verbose_name='Qualification Detail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit UIDAI Aadhaar number', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optional +91 prefix).', regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')], verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, dots, hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]*$")], verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, dots, hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]*$")], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, dots, hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]*$")], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optional +91 prefix).', regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optional +91 prefix).', regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')], verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optional +91 prefix).', regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')], verbose_name='Work Phone'),
        ),
    ]
