# Generated by Django 4.2.30 on 2026-07-04 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_employee_qualification_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, dots, hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]*$")], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, dots, hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]*$")], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='PIN Code'),
        ),
    ]
