# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_quantity'),
        ('employee', '0016_alter_employeeworkinformation_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_lot_number_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetlot', verbose_name='Batch No'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Current User'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_by_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='employee.employee', verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_employee', to='employee.employee', verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory', verbose_name='Asset Category'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='requested_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_employee', to='employee.employee', verbose_name='Requesting User'),
        ),
    ]
