# Generated by Django 6.0.6 on 2026-06-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_asset_category_id_and_more'),
        ('base', '0014_announcementcomment_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdocuments',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='assetreport',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='returnimages',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
