# Generated by Django 6.0.6 on 2026-06-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_assetdocuments_company_id_assetreport_company_id_and_more'),
        ('employee', '0018_actiontype_company_id_policymultiplefile_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='asset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to_employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_employee', to='employee.employee', verbose_name='Assigned To'),
        ),
    ]
