# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_assetassignment_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocuments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='returnimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
