# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('pms', '0003_historicalobjective_is_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answer', to='pms.feedback'),
        ),
        migrations.AlterField(
            model_name='employeekeyresult',
            name='key_result_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_key_result', to='pms.keyresult', verbose_name='Key result'),
        ),
        migrations.AlterField(
            model_name='employeeobjective',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_objective', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeobjective',
            name='objective_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_objective', to='pms.objective', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='keyresultfeedback',
            name='feedback_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_key_result', to='pms.feedback'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='question_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.questiontemplate', verbose_name='Question Template'),
        ),
        migrations.AlterField(
            model_name='meetingsanswer',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_answer', to='pms.meetings'),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='pms.question'),
        ),
    ]
