# Generated by Django 6.0.6 on 2026-06-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_announcementview_company_id_attachment_company_id_and_more'),
        ('pms', '0004_alter_answer_feedback_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
