# Generated by Django 4.2.30 on 2026-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_anonymousfeedback_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeekeyresult',
            name='progress_type',
            field=models.CharField(blank=True, choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', (('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')))], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeekeyresult',
            name='progress_type',
            field=models.CharField(blank=True, choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', (('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')))], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeyresult',
            name='progress_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', (('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')))], default='%', max_length=60, verbose_name='Progress Type'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='progress_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', (('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')))], default='%', max_length=60, verbose_name='Progress Type'),
        ),
    ]
