# Generated by Django 4.2.30 on 2026-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employeeworkinformation_department_id_and_more'),
        ('base', '0017_backfill_single_company_org_settings'),
        ('pms', '0006_alter_employeekeyresult_progress_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobposition', verbose_name='Job Position'),
        ),
    ]
