# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylinx_backup', '0002_remove_googledrivebackup_service_account_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivebackup',
            name='oauth_credentials_file',
            field=models.FileField(blank=True, help_text='Make sure your file is in JSON format and contains your Google OAuth 2.0 client credentials (web application type)', null=True, upload_to='gdrive_oauth_credentials_file', validators=[skylinx.validators.SafeMimeValidator()], verbose_name='OAuth Credentials File'),
        ),
    ]
