# Generated by Django 6.0.6 on 2026-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylinx_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skylinxuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
