# Generated by Django 5.2 on 2026-06-17 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('employee_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled_features', models.JSONField(blank=True, default=list)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'License configuration',
                'verbose_name_plural': 'License configuration',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('billing_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_limit', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('employee_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.plan')),
            ],
        ),
    ]
