# Generated by Django 5.2 on 2026-06-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
