# Generated by Django 6.0.6 on 2026-07-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0020_alter_worktype_geofence_exempt'),
        ('employee', '0023_alter_employee_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonnectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='konnect/')),
                ('category', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcements'), ('birthday', 'Birthday'), ('anniversary', 'Work Anniversary'), ('new_joiner', 'New Joiner')], default='general', max_length=20)),
                ('pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konnect_posts', to='employee.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konnect_posts', to='base.company')),
                ('mentions', models.ManyToManyField(blank=True, related_name='konnect_mentions', to='employee.employee')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KonnectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='konnect.konnectpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KonnectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='konnect.konnectpost')),
            ],
            options={
                'unique_together': {('post', 'employee')},
            },
        ),
    ]
