# Generated by Django 6.0.6 on 2026-07-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0020_alter_worktype_geofence_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('ifsc_code', models.CharField(blank=True, max_length=30)),
                ('account_type', models.CharField(blank=True, max_length=40)),
                ('corporate_id', models.CharField(blank=True, max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bank_accounts', to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('official_contact', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('domain_name', models.CharField(blank=True, max_length=120)),
                ('industry_type', models.CharField(blank=True, max_length=120)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=40)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('tan', models.CharField(blank=True, max_length=20)),
                ('gst', models.CharField(blank=True, max_length=30)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('auditors', models.JSONField(blank=True, default=list)),
                ('company_secretaries', models.JSONField(blank=True, default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='base.company')),
            ],
        ),
    ]
