# Generated by Django 6.0.6 on 2026-06-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('skylinx_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skylinx_documents.documentrequest'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
    ]
