# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylinx_documents', '0002_alter_document_document_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Document'),
        ),
    ]
