# Generated by Django 5.2 on 2026-06-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollsettings_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filingstatus',
            options={'ordering': ['-id'], 'verbose_name': 'Tax Regime', 'verbose_name_plural': 'Tax Regimes'},
        ),
        migrations.AlterModelOptions(
            name='taxbracket',
            options={'verbose_name': 'Income Slab', 'verbose_name_plural': 'Income Slabs'},
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='position',
            field=models.CharField(choices=[('prefix', 'Prefix'), ('postfix', 'Suffix')], default='prefix', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='filing_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.filingstatus', verbose_name='Tax Regime'),
        ),
    ]
