# Generated by Django 5.2 on 2026-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_currency_dollar_to_rupee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel & Conveyance'), ('fuel', 'Fuel / Mileage'), ('mobile', 'Mobile & Internet'), ('medical', 'Medical'), ('food', 'Food & Meals'), ('books', 'Books & Professional Development'), ('entertainment', 'Client Entertainment')], max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='wage_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=250, verbose_name='Wage Type'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='wage_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=250, verbose_name='Wage Type'),
        ),
    ]
