# Generated by Django 6.0.6 on 2026-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_reimbursement_category_alter_contract_wage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='type',
            field=models.CharField(choices=[('reimbursement', 'Expense'), ('bonus_encashment', 'Bonus Point Encashment'), ('leave_encashment', 'Leave Encashment')], default='reimbursement', max_length=16),
        ),
    ]
