# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_asset_category_id_and_more'),
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
        ('leave', '0006_alter_availableleave_leave_type_id_and_more'),
        ('payroll', '0008_alter_reimbursement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.worktype', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_set', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='filing_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payroll.filingstatus', verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.jobrole', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.worktype', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='filingstatus',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='asset_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='leave_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
    ]
