# Generated by Django 6.0.6 on 2026-06-26 20:11

import django.db.models.deletion
import payroll.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_employee_id_and_more'),
        ('base', '0015_announcementview_company_id_attachment_company_id_and_more'),
        ('payroll', '0010_form16document_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideAttendance',
            fields=[
                ('attendance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.attendance')),
            ],
            options={
                'abstract': False,
            },
            bases=('attendance.attendance',),
        ),
        migrations.AddField(
            model_name='reimbursementfile',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='reimbursementmultipleattachment',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for this allowance', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount_per_one_hr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The fixed amount for one hour overtime that are validated             and approved the overtime attendance', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='end_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The end amount of the pay-head range', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='if_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount of the pay-head', max_digits=15),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum amount for the allowance', max_digits=15, null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='per_attendance_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The attendance fixed amount for one validated attendance', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='per_children_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The fixed amount per children', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The percentage of based on', max_digits=15, null=True, validators=[payroll.models.models.rate_validator]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='shift_per_attendance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The fixed amount for one validated attendance with that shift', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='start_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The start amount of the pay-head range', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='work_type_per_attendance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The fixed amount for one validated attendance with that work type', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deduction_for_one_leave_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Deduction For One Leave Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for this deduction', max_digits=15, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employer_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[payroll.models.models.rate_validator]),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='end_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The end amount of the pay-head range', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='if_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount of the pay-head', max_digits=15),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum amount for the deduction', max_digits=15, null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The percentage of based on', max_digits=15, null=True, validators=[payroll.models.models.rate_validator], verbose_name='Employee rate'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='start_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The start amount of the pay-head range', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='deduction_for_one_leave_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Deduction For One Leave Amount'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='contract_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='installment Amount'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='contract_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='ad_to_encash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available Days to encash', max_digits=15, verbose_name='Available days'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='cfd_to_encash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carry Forward Days to encash', max_digits=15, verbose_name='Carry forward days'),
        ),
        migrations.DeleteModel(
            name='WorkRecord',
        ),
    ]
