# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_overrideattendance_reimbursementfile_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='form16document',
            name='document',
            field=models.FileField(upload_to='payroll/form16/', validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Form 16 Document'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attachment',
            field=models.FileField(null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='reimbursementfile',
            name='file',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='reimbursementmultipleattachment',
            name='attachment',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
