# Generated by Django 4.2.30 on 2026-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_backfill_single_company_org_settings'),
        ('payroll', '0012_alter_contract_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='base.jobrole', verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='base.worktype', verbose_name='Work Type'),
        ),
    ]
