# Generated by Django 4.2.30 on 2026-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_contract_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel & Conveyance'), ('fuel', 'Fuel / Mileage'), ('medical', 'Medical'), ('food', 'Food & Meals'), ('books', 'Books & Professional Development'), ('others', 'Others')], max_length=20, null=True, verbose_name='Category'),
        ),
    ]
