# Generated by Django 6.0.6 on 2026-06-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylinx_theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytheme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
    ]
