# Generated by Django 5.2 on 2026-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
