# Generated by Django 6.0.6 on 2026-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_trial_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='feature_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
