# Generated by Django 6.0.6 on 2026-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_feature_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='seat_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
