# Generated by Django 4.2.30 on 2026-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_yearly_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('api_base', models.CharField(default='https://api.groq.com/openai/v1', max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(default='llama-3.3-70b-versatile', max_length=120)),
                ('allow_employee', models.BooleanField(default=True)),
                ('allow_hr', models.BooleanField(default=True)),
                ('allow_ceo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
            },
        ),
    ]
