# Generated by Django 4.2.30 on 2026-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='max_action_level',
            field=models.CharField(choices=[('guidance', 'Guidance only — explains, never touches data'), ('suggest', 'Suggest + human confirms — proposes an action, a person must click confirm'), ('execute', 'AI executes directly — not yet built; behaves as Suggest for now')], default='guidance', max_length=20),
        ),
    ]
