# Generated by Django 4.2.30 on 2026-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_aisettings_max_action_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='max_action_level',
            field=models.CharField(choices=[('guidance', 'Guidance only — explains, never touches data'), ('suggest', 'Suggest + human confirms — proposes an action, a person must click confirm'), ('execute', 'AI executes directly — can approve/reject pending leave requests on instruction; everything else stays Suggest')], default='guidance', max_length=20),
        ),
    ]
