# Generated by Django 5.2 on 2026-07-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_support_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportsettings',
            name='forward_email',
            field=models.EmailField(blank=True, default='', help_text='Every new support ticket is emailed here, sent via whichever mail server the raising company/its fallback primary is configured with. Leave blank to rely on in-app notifications only.', max_length=254, verbose_name='Support notification email'),
        ),
        migrations.AlterField(
            model_name='supportsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_owner', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='subscriptions.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
