# Generated by Django 4.2.30 on 2026-07-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_onboardinginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvite',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
    ]
