# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('project', '0002_alter_project_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
