# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Project File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()], verbose_name='Task File'),
        ),
    ]
