# Generated by Django 5.2 on 2026-06-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rosterpublishlog_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklatecomeearlyout',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_enabled_company', to='base.company', verbose_name='Company'),
        ),
    ]
