# Generated by Django 5.2 on 2026-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tracklatecomeearlyout_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_format',
            field=models.CharField(blank=True, default='DD-MM-YYYY', max_length=30, null=True),
        ),
    ]
