# Generated by Django 5.2 on 2026-06-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_is_new_employee'),
        ('base', '0006_alter_company_date_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='base.company')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_link', to='auth.group')),
            ],
        ),
    ]
