# Generated by Django 6.0.6 on 2026-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_work_from_office_to_onsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='is_optional',
            field=models.BooleanField(default=False, help_text="If on, employees may apply leave on this day. If off, it's a mandatory holiday and no leave can be applied.", verbose_name='Optional Holiday'),
        ),
    ]
