# Generated by Django 6.0.6 on 2026-06-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_holidays_is_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_url', models.URLField(default='https://skylinxpartial.ccbp.tech', verbose_name='Terms & Conditions / Privacy URL')),
            ],
        ),
    ]
