# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_mobileattendancedetail_mobilelocationlog'),
        ('base', '0012_rename_company_skylinx_to_emplinx'),
        ('employee', '0016_alter_employeeworkinformation_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricattendance',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enabled_company', to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyleaves',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='grace_time_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift', to='attendance.gracetime', verbose_name='Grace Time'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedule', to='base.employeeshiftday'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='job_position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='employee_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_accounts', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='shift1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift1', to='base.employeeshift', verbose_name='Shift 1'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='shift2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift2', to='base.employeeshift', verbose_name='Shift 2'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='current_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_shift', to='base.employeeshift', verbose_name='Current Shift'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='next_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_shift', to='base.employeeshift', verbose_name='Next Shift'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='rotating_shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rotatingshift', verbose_name='Rotating Shift'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='work_type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type1', to='base.worktype', verbose_name='Work Type 1'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='work_type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type2', to='base.worktype', verbose_name='Work Type 2'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='current_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_work_type', to='base.worktype', verbose_name='Current Work Type'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='next_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_work_type', to='base.worktype', verbose_name='Next Work Type'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='rotating_work_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rotatingworktype', verbose_name='Rotating Work Type'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_request', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='previous_shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_shift', to='base.employeeshift', verbose_name='Previous Shift'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='reallocate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reallocate_shift_request', to='employee.employee', verbose_name='Reallocate Employee'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_shift', to='base.employeeshift', verbose_name='Requesting Shift'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_type_request', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='previous_work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_work_type', to='base.worktype', verbose_name='Previous Work Type'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='work_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_work_type', to='base.worktype', verbose_name='Requesting Work Type'),
        ),
    ]
