# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_announcementview_company_id_attachment_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='baserequestfile',
            name='file',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.FileField(null=True, upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='file',
            field=models.FileField(upload_to='legal/', validators=[skylinx.validators.SafeMimeValidator()], verbose_name='PDF file'),
        ),
    ]
