# Generated by Django 4.2.30 on 2026-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_backfill_single_company_org_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_action_level',
            field=models.CharField(choices=[('guidance', 'Guidance only'), ('suggest', 'Suggest + human confirms'), ('execute', 'AI executes directly (not yet available)')], default='guidance', max_length=20),
        ),
    ]
