# Generated by Django 6.0.6 on 2026-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_worktype_geofence_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='geofence_exempt',
            field=models.BooleanField(default=False, help_text='Employees on this work type (e.g. Hybrid, Work From Home) skip geofence checks on check-in/out and continuous location alerts.', verbose_name='Exempt from Geo-fencing'),
        ),
    ]
