# Generated by Django 4.2.30 on 2026-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_worktype_geofence_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicemailconfiguration',
            name='purpose',
            field=models.CharField(blank=True, help_text="Optional tag, e.g. 'client_intake', for a dedicated mailbox.", max_length=40, null=True),
        ),
    ]
