# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0002_alter_offboardingemployee_notice_period_ends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboardingnote',
            name='stage_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='offboarding.offboardingstage'),
        ),
        migrations.AlterField(
            model_name='offboardingtask',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offboarding.offboardingstage', verbose_name='Stage'),
        ),
    ]
