# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0004_employeetask_company_id_exitreason_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboardingstagemultiplefile',
            name='attachment',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
