# Generated by Django 6.0.6 on 2026-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_employee_first_name_and_more'),
        ('geofencing', '0002_geofencing_enforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencing',
            name='exempted_employees',
            field=models.ManyToManyField(blank=True, help_text='These employees skip geofence checks entirely, regardless of location.', related_name='geofence_exemptions', to='employee.employee', verbose_name='Exempted Employees'),
        ),
    ]
