# Generated by Django 6.0.6 on 2026-06-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('recruitment', '0006_alter_candidate_job_position_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestage',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_stage', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatestage',
            name='onboarding_stage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='onboarding.onboardingstage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='candidatetask',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_task', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatetask',
            name='onboarding_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask'),
        ),
        migrations.AlterField(
            model_name='candidatetask',
            name='stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_task', to='onboarding.onboardingstage'),
        ),
        migrations.AlterField(
            model_name='onboardingportal',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_portal', to='recruitment.candidate'),
        ),
    ]
