# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_candidatestage_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingportal',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='employee/profile', validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
