# Generated by Django 6.0.6 on 2026-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_biometricattendance_company_id_and_more'),
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevices',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
