# Generated by Django 6.0.6 on 2026-06-24 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceovertime_year'),
        ('employee', '0014_sync_state_drop_legacy_salary_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_selfie', models.ImageField(blank=True, null=True, upload_to='selfies/check_in/')),
                ('check_in_lat', models.FloatField(blank=True, null=True)),
                ('check_in_lng', models.FloatField(blank=True, null=True)),
                ('check_out_selfie', models.ImageField(blank=True, null=True, upload_to='selfies/check_out/')),
                ('check_out_lat', models.FloatField(blank=True, null=True)),
                ('check_out_lng', models.FloatField(blank=True, null=True)),
                ('within_geofence', models.BooleanField(default=True)),
                ('check_out_within_geofence', models.BooleanField(default=True)),
                ('attendance_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_detail', to='attendance.attendanceactivity', verbose_name='Attendance Activity')),
            ],
            options={
                'verbose_name': 'Mobile Attendance Detail',
                'verbose_name_plural': 'Mobile Attendance Details',
            },
        ),
        migrations.CreateModel(
            name='MobileLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('gps_enabled', models.BooleanField(default=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_location_logs', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Mobile Location Log',
                'verbose_name_plural': 'Mobile Location Logs',
                'ordering': ['-captured_at'],
            },
        ),
    ]
