# Generated by Django 6.0.6 on 2026-06-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_mobileattendancedetail_mobilelocationlog'),
        ('employee', '0017_alter_employeeworkinformation_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='batch_attendance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.batchattendance', verbose_name='Batch Attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendanceactivity',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_activities', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendancelatecomeearlyout',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_come_early_out', to='attendance.attendance', verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='attendanceovertime',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overtime', to='employee.employee', verbose_name='Employee'),
        ),
    ]
