# Generated by Django 6.0.6 on 2026-06-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerequestcomment_company_id_and_more'),
        ('employee', '0018_actiontype_company_id_policymultiplefile_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendances', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendanceactivity',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_activities', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendanceovertime',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_overtime', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='attendancerequestcomment',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='workrecords',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Employee'),
        ),
    ]
