# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.models
import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequestfile',
            name='file',
            field=models.FileField(upload_to=skylinx.models.upload_path, validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='mobileattendancedetail',
            name='check_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/check_in/', validators=[skylinx.validators.SafeMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='mobileattendancedetail',
            name='check_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/check_out/', validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
