# Generated by Django 5.2 on 2026-07-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_latecomeearlyout_anomaly_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelatecomeearlyout',
            name='type',
            field=models.CharField(choices=[('late_come', 'Late Come'), ('early_out', 'Early Out'), ('missing_checkout', 'Forgot to Checkout')], max_length=20, verbose_name='Type'),
        ),
    ]
