# Generated by Django 6.0.6 on 2026-06-27 06:02

import skylinx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0002_alter_facedetection_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefacedetection',
            name='image',
            field=models.ImageField(upload_to='', validators=[skylinx.validators.SafeMimeValidator()]),
        ),
    ]
